### ISSUE TITLE
Доделать взаимодействие с Users-Service 🚑🚑🚑🚑

### ISSUE THREAD

**Issue by pipichinka** [Concerts-Mate/Bot#18]
Нужно реализовать общение с бэкендом, дёргая endpoint-ы для работы с пользователями.

**Comment by pipichinka** [comment]
![Cirilla.gif](https://github.com/Concerts-Mate/Bot/assets/89928654/5ea52f48-c968-48e8-be46-f0d9abf96861)

**Comment by pipichinka** [comment]
А оно всё, написано?

**Comment by llirik42** [comment]
Там просто же другие issues появились, которые суммарно охватывают это. Ваще без б, если хочешь открыть заново - открывай🚀

**Comment by llirik42** [comment]
@pipichinka
