### ISSUE TITLE
Докер-обрез с MongoDB

### ISSUE THREAD

**Issue by llirik42** [Concerts-Mate/Bot#5]
Для бота нужен MongoDB, чтобы сохранять состояние пользователей там, а не в оперативной памяти, чтобы перезагрузки и отключения бота ничего не ломали. Срок - 2 недели

**Comment by dura0ok** [comment]
@llirik42 А @Wooshey1411 точно сможет это себе добавить?

**Comment by dura0ok** [comment]
@Wooshey1411 что с задачей?
@llirik42 ?
