### ISSUE TITLE
User Flow

### ISSUE THREAD

**Issue by dura0ok** [Concerts-Mate/Bot#7]
> User Flow выраженный в экранах
Должно быть распределено по функционалу. Условно - регистрация пользователя одна последовательность, добавление дополнительного плейлиста ПОСЛЕ регистрации другая и т.д.. Распредели по функционалу в общем

Перенеси все экраны сюда в обсуждение issue, опиши что готово на данный момент
Срок - неделя

**Comment by Wooshey1411** [comment]
Я сделал на доске miro.

**Comment by Wooshey1411** [comment]
### Пользователь вводит /start. 
Здесь 2 варианта
1. Если пользователь не был зарегистрирован, то он начинает проходить процесс регистрации.
2. Если пользователь был зарегистрирован, то он сразу переходит на главное меню. Как на данном экране
![Screenshot_20240428_003914](https://github.com/Concerts-Mate/Bot/assets/113329986/b3fd8074-6672-4709-9706-fae48f11a388)

**Comment by Wooshey1411** [comment]
### Регистрация
Идёт в два этапа.
1. Ввод городов: для первого города пользователю предлагается ввести название города или отправить свою геолокацию, нажав на кнопку.
![image](https://github.com/Concerts-Mate/Bot/assets/113329986/41461112-10cd-4ce4-be4f-25f8ea00b5d9)
Причём есть один особый случай: если пользователь ввёл неточное название города - предлагается исправленный вариант и вариант выбора что делать с ним
![image(1)](https://github.com/Concerts-Mate/Bot/assets/113329986/52ee5b1c-df96-4485-919e-898d22bdd4e7)
Далее пользователь может вводить города по одному или сразу перейти на следующий этап регистрации
![image(3)](https://github.com/Concerts-Mate/Bot/assets/113329986/04fefc30-4f59-4a97-bcea-fa0755fe5eb7)
2. Ввод ссылок на плейлисты: пользователю предлагается ввести ссылку на плейлист
![image(4)](https://github.com/Concerts-Mate/Bot/assets/113329986/e5847c7c-baae-438f-be2a-52816312c084)
Далее пользователь может вводить ссылки по одной или сразу окончить регистрацию.
![image(5)](https://github.com/Concerts-Mate/Bot/assets/113329986/e8c256b0-c022-4540-91fd-435ef6af96bc)
По окончании регистрации пользователь перегодит на главное меню
![image(6)](https://github.com/Concerts-Mate/Bot/assets/113329986/81947fd7-9034-4411-9584-bc2af6623c0d)

**Comment by Wooshey1411** [comment]
### Изменение данных
Если в меню выбрать 'Изменить данные', то пользователю открывается новое меню где предлагается выбрать действие, направленное на изменение данных по городам/ссылкам, их всего 4.
![image](https://github.com/Concerts-Mate/Bot/assets/113329986/7a7bcb2a-9c22-4401-b2b3-ac548343c6c9)
1. Добавление города: пользователю предлагается ввести название города
![image(1)](https://github.com/Concerts-Mate/Bot/assets/113329986/fc353ca1-a901-47db-a202-7fa499b09a06)
если пользователь ввёл неточное название города - предлагается исправленный вариант и вариант выбора что делать с ним
![image(2)](https://github.com/Concerts-Mate/Bot/assets/113329986/f07f3bee-d298-4e42-8b02-d813679444ad)
2. Добавление ссылки на плейлист: пользователю предлагается ввести ссылку
![image(3)](https://github.com/Concerts-Mate/Bot/assets/113329986/3dd908db-323a-40d5-bf90-75352929e4e7)
3. Удаление города: пользователю выводится список городов в виде кнопок, нажав на которую пользователь удаляет город
![image(4)](https://github.com/Concerts-Mate/Bot/assets/113329986/e3661b18-2ebb-4c3b-a5ce-984d4d6b5508)
4. Удаление ссылки: пользователю выводится список ссылок сообщением с номерами и номера в виде кнопок, нажав на которую пользователь удаляет ссылку
![image(5)](https://github.com/Concerts-Mate/Bot/assets/113329986/13e269be-23e5-47a4-b3d4-879105321a0a)

**Comment by Wooshey1411** [comment]
### Инструменты
Нажав в главном меню на 'Инструменты' пользователю открывается меню, где представлены инструменты для взаимодействия с ботом.
![image](https://github.com/Concerts-Mate/Bot/assets/113329986/56ecdb04-27ba-47ae-8dd5-e2525293b310)
1. Получить возможные концерты: Пользователю отправляется список концерты на которые он может сходить
![image(1)](https://github.com/Concerts-Mate/Bot/assets/113329986/de00b106-fb5e-4890-8503-87cc2892a736)

**Comment by Wooshey1411** [comment]
### FAQ
Если в меню выбрать 'FAQ', то пользователю открывается новое меню, где он сможет узнать что-то о боте или связаться с разработчиком
![image(2)](https://github.com/Concerts-Mate/Bot/assets/113329986/13028051-c95e-4109-88da-e3909db4b93d)
1. 'Что умеет это бот': пользователю показывается описание бота
![image(3)](https://github.com/Concerts-Mate/Bot/assets/113329986/a8074076-254e-41af-9a5f-896fbd955103)
2. 'Связь с разработчиком': пользователю показывается средство связи с разработчиком
![image(4)](https://github.com/Concerts-Mate/Bot/assets/113329986/6fb273f8-4a26-40be-89fc-c8b65553cd24)

**Comment by Wooshey1411** [comment]
### Показ информации о пользователе
Если в меню выбрать 'Информация о пользователе', то пользователю открывается новое меню где он сможет узнать какие по каким городам ищутся концерты и по каким ссылкам мы получаем его данные
![image](https://github.com/Concerts-Mate/Bot/assets/113329986/2f5c0d8e-5a27-4913-ae5c-0a8953ddaf0e)
1. 'Города': пользователю показывается список городов
![image(1)](https://github.com/Concerts-Mate/Bot/assets/113329986/d67da078-d2f4-4ce0-829e-2966be8bd8a9)
2. 'Плейлисты': пользователю показывается список ссылок на плейлисты
![image(2)](https://github.com/Concerts-Mate/Bot/assets/113329986/79e84c4b-4b49-4197-b56b-becbb72491fd)

**Comment by llirik42** [comment]
Было сделано давно
