### ISSUE TITLE
Исследовательская задача. Telegram WEB 🪲 баг

### ISSUE THREAD

**Issue by dura0ok** [Concerts-Mate/Bot#9]
🪲 Срок 3 недели 🪲
Починить работу телеграм бота в Telegram Web
> Починить клавитуру
> Узнать почему не убирается клавитура, откуда лаги

**Comment by dura0ok** [comment]
https://t.me/aiogram
Рекомендую спросить например тут

**Comment by Wooshey1411** [comment]
Поспрашивал людей, говорят что проблема есть - это лаги самого web telegram.
Вдобавок я решил использовать другую функцию, не работает. В чём суть - внутренняя клавиатура не удаляется у пользователей web-telegram, в других клиентах (desktop/mobile) работает. Это косметическая проблема у малочисленного количества пользователей веб версии, просто клавиатура не стирается - логику не ломает, всё остальное работает.
![image](https://github.com/Concerts-Mate/Bot/assets/113329986/23923900-d945-4f9f-b849-c03e487bb661)

**Comment by Wooshey1411** [comment]
https://github.com/Ajaxy/telegram-tt/issues/343
issue в репозитории web-telegram с схожей проблемой.
